In [12]:
import seaborn as sns 
import pandas as pd 
from matplotlib import pyplot as plt
import numpy as np

# Numpy is a useful package you will see frequently. It can run quickly. 

In [52]:
url = "https://raw.githubusercontent.com/shionguha/inf1340-programmingfordatascience-fa22/main/data/titanic_dataset.csv"
df = pd.read_csv(url)
df

survived  pclass                                             name  \
0            1       1                    Allen, Miss. Elisabeth Walton   
1            1       1                   Allison, Master. Hudson Trevor   
2            0       1                     Allison, Miss. Helen Loraine   
3            0       1             Allison, Mr. Hudson Joshua Creighton   
4            0       1  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...        ...     ...                                              ...   
1304         0       3                             Zabour, Miss. Hileni   
1305         0       3                            Zabour, Miss. Thamine   
1306         0       3                        Zakarian, Mr. Mapriededer   
1307         0       3                              Zakarian, Mr. Ortin   
1308         0       3                               Zimmerman, Mr. Leo   

         sex      age  sibsp  parch  ticket      fare  
0     female  29.0000      0      0   24160  211.3375  
1       male   0.9167      1      2  113781  151.5500  
2     female   2.0000      1      2  113781  151.5500  
3       male  30.0000      1      2  113781  151.5500  
4     female  25.0000      1      2  113781  151.5500  
...      ...      ...    ...    ...     ...       ...  
1304  female  14.5000      1      0    2665   14.4542  
1305  female   0.0000      1      0    2665   14.4542  
1306    male  26.5000      0      0    2656    7.2250  
1307    male  27.0000      0      0    2670    7.2250  
1308    male  29.0000      0      0  315082    7.8750  

[1309 rows x 9 columns]

In [3]:
# Making a DataFrame into a Numpy array is easy: 
df_np = df.values
df_np

array([[1, 1, 'Allen, Miss. Elisabeth Walton', ..., 0, '24160', 211.3375],
       [1, 1, 'Allison, Master. Hudson Trevor', ..., 2, '113781', 151.55],
       [0, 1, 'Allison, Miss. Helen Loraine', ..., 2, '113781', 151.55],
       ...,
       [0, 3, 'Zakarian, Mr. Mapriededer', ..., 0, '2656', 7.225],
       [0, 3, 'Zakarian, Mr. Ortin', ..., 0, '2670', 7.225],
       [0, 3, 'Zimmerman, Mr. Leo', ..., 0, '315082', 7.875]],
      dtype=object)

In [54]:
#you can make a numpy array of a certain column 
df['age'].values

array([29.    ,  0.9167,  2.    , ..., 26.5   , 27.    , 29.    ])

In [56]:
#you can find the shape of a numpy array 
df_np.shape

(1309, 9)

# Slicing a numpy array 

In [57]:
df_np

array([[1, 1, 'Allen, Miss. Elisabeth Walton', ..., 0, '24160', 211.3375],
       [1, 1, 'Allison, Master. Hudson Trevor', ..., 2, '113781', 151.55],
       [0, 1, 'Allison, Miss. Helen Loraine', ..., 2, '113781', 151.55],
       ...,
       [0, 3, 'Zakarian, Mr. Mapriededer', ..., 0, '2656', 7.225],
       [0, 3, 'Zakarian, Mr. Ortin', ..., 0, '2670', 7.225],
       [0, 3, 'Zimmerman, Mr. Leo', ..., 0, '315082', 7.875]],
      dtype=object)

In [8]:
# Getting the 5th column:
df_np[:,4] #after the comma, you get the columns

array([29.0, 0.9167, 2.0, ..., 26.5, 27.0, 29.0], dtype=object)

In [9]:
# Getting the first row: 
df_np[0,:] 

array([1, 1, 'Allen, Miss. Elisabeth Walton', 'female', 29.0, 0, 0,
       '24160', 211.3375], dtype=object)

This slicing is similar to loc 

In [10]:
# Select the 6th column from the first three rows
df_np[0:3,5]

array([0, 1, 1], dtype=object)

In [49]:
df_np[::-1] #get the rows from the bottom up 

array([[0, 3, 'Zimmerman, Mr. Leo', ..., 0, '315082', 7.875],
       [0, 3, 'Zakarian, Mr. Ortin', ..., 0, '2670', 7.225],
       [0, 3, 'Zakarian, Mr. Mapriededer', ..., 0, '2656', 7.225],
       ...,
       [0, 1, 'Allison, Miss. Helen Loraine', ..., 2, '113781', 151.55],
       [1, 1, 'Allison, Master. Hudson Trevor', ..., 2, '113781', 151.55],
       [1, 1, 'Allen, Miss. Elisabeth Walton', ..., 0, '24160', 211.3375]],
      dtype=object)

# Other useful things Numpy can do...

In [22]:
x = np.arange(11)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [61]:
np.arange(0,10,2) #start, stop, step 

array([0, 2, 4, 6, 8])

In [48]:
a = np.arange(2,11)
print(a)

a.reshape(3,3)

[ 2  3  4  5  6  7  8  9 10]


array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [64]:
x= np.arange(11)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
np.random.shuffle(x)
print(x)

[ 8  3  2  0  5  9  4 10  7  6  1]


In [26]:
np.random.permutation(11) #Randomly permute a sequence

array([ 2,  8,  7, 10,  3,  0,  9,  5,  4,  6,  1])

In [47]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
#some useful functionalities from numpy (may not be too useful for this class)
np.random.normal(size=5) #generate five random numbers from the normal distribution #by default the mean is 0

array([-0.37999084,  0.21094867,  0.35470304,  0.32875305,  0.56158393])

In [66]:
#we see in line that mean converges to 0 (setting by default)
np.mean(np.random.normal(size=10000000))

0.0005261894579218798

In [68]:
x = np.random.normal(size=(10,4))
print('original array')
print(x)

y= x[:4, :]
print("\n First 4 rows of the above array:")
print(y)

original array
[[-1.29457156e+00  3.56531377e-01 -9.22600614e-01  4.23404587e-01]
 [-1.02622311e-01 -2.01677835e-01 -4.78032295e-01  1.77745502e+00]
 [-1.28955554e+00  1.09797174e-01  2.39817957e-01 -6.17548496e-01]
 [ 8.23072600e-01 -9.73035095e-01  1.05118931e+00  2.36965774e+00]
 [ 6.70062292e-02 -9.20375280e-01  1.65227243e+00 -3.61509592e-01]
 [ 3.97692615e-01  1.32078787e+00 -9.30808143e-01  4.47319689e-01]
 [-5.69752938e-01 -3.52238216e-01 -9.80201698e-02  2.12631446e-04]
 [ 3.61420867e-01 -1.99276785e+00 -8.61558479e-01 -3.97585976e-01]
 [ 3.99017506e-01  8.88714638e-01  1.84017783e+00  7.25371734e-01]
 [ 4.86179747e-01 -1.40377849e+00  2.69952746e-02  1.12246697e+00]]

 First 4 rows of the above array:
[[-1.29457156  0.35653138 -0.92260061  0.42340459]
 [-0.10262231 -0.20167784 -0.4780323   1.77745502]
 [-1.28955554  0.10979717  0.23981796 -0.6175485 ]
 [ 0.8230726  -0.9730351   1.05118931  2.36965774]]


In [41]:
new_arr = np.array([[1990,2000],[30,200]])
print("the original array:")
print(new_arr)

print("Sorting the array along the first axis:") #think vertical 
print(np.sort(new_arr, axis=0))

print("Sorting the array along the last axis:") #think horizontal 
print(np.sort(new_arr))


the original array:
[[1990 2000]
 [  30  200]]
Sorting the array along the first axis:
[[  30  200]
 [1990 2000]]
Sorting the array along the last axis:
[[1990 2000]
 [  30  200]]


In [42]:
a = np.array([[10,40],[30,20]])
print("Original array:")
print(a)

print("Sort the array along the first axis:")
print(np.sort(a, axis=0))

print("Sort the array along the last axis:")
print(np.sort(a))

print("Sort the flattened array:")
print(np.sort(a, axis=None))

Original array:
[[10 40]
 [30 20]]
Sort the array along the first axis:
[[10 20]
 [30 40]]
Sort the array along the last axis:
[[10 40]
 [20 30]]
Sort the flattened array:
[10 20 30 40]


# Some Math with numpy 

In [69]:
vector_arr = np.array([1,4,5,6,11,14])
vector_arr

array([ 1,  4,  5,  6, 11, 14])

In [70]:
#get the sum of the elements in the array 
vector_arr.sum()

41

In [31]:
vector_arr.mean()

6.833333333333333

In [32]:
vector_arr.std()

4.374801582802229

In [36]:
np.median(vector_arr)

5.5

In [15]:
vector_arr - 4

array([-3,  0,  1,  2,  7, 10])

In [71]:
# get the natural log of the elements in the vector 
np.log(vector_arr)

array([0.        , 1.38629436, 1.60943791, 1.79175947, 2.39789527,
       2.63905733])

In [17]:
# Numpy and Pandas works well together
df['age'] = np.log(df['age'])
df

/opt/conda/lib/python3.8/site-packages/pandas/core/arraylike.py:397: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)


survived  pclass                                             name  \
0            1       1                    Allen, Miss. Elisabeth Walton   
1            1       1                   Allison, Master. Hudson Trevor   
2            0       1                     Allison, Miss. Helen Loraine   
3            0       1             Allison, Mr. Hudson Joshua Creighton   
4            0       1  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...        ...     ...                                              ...   
1304         0       3                             Zabour, Miss. Hileni   
1305         0       3                            Zabour, Miss. Thamine   
1306         0       3                        Zakarian, Mr. Mapriededer   
1307         0       3                              Zakarian, Mr. Ortin   
1308         0       3                               Zimmerman, Mr. Leo   

         sex       age  sibsp  parch  ticket      fare  
0     female  3.367296      0      0   24160  211.3375  
1       male -0.086975      1      2  113781  151.5500  
2     female  0.693147      1      2  113781  151.5500  
3       male  3.401197      1      2  113781  151.5500  
4     female  3.218876      1      2  113781  151.5500  
...      ...       ...    ...    ...     ...       ...  
1304  female  2.674149      1      0    2665   14.4542  
1305  female      -inf      1      0    2665   14.4542  
1306    male  3.277145      0      0    2656    7.2250  
1307    male  3.295837      0      0    2670    7.2250  
1308    male  3.367296      0      0  315082    7.8750  

[1309 rows x 9 columns]

In [51]:
a = np.array([0,1,2,4,6,8])
b = np.array([1,3,5,7,9,10])

a+b

array([ 1,  4,  7, 11, 15, 18])

# Numpy can be multi dimensional 

In [19]:
array_3d = np.array([
    [
        [4,1,2],
        [4,2,3]
    ],
    [
        [2,4,6],
        [1,8,7]
    ],
])
array_3d.shape

(2, 2, 3)

In [72]:
#slicing works similarly what would be the value of this? 
array_3d[0,0,2]

2